"""Reusable components for the SONiC Scout change-risk agent."""

from .gitcmd import GitError, GitRepo
from .incidents import Incident, mine_incidents, read_corpus, summarize, write_corpus
from .ingest import resolve
from .models import ChangeSet, ChangeSetSpec, CommitInfo, FileDiff
from .provider import (
    Completion,
    Message,
    ModelSpec,
    Provider,
    ProviderError,
    ReplayMiss,
    ReplayProvider,
    RecordingProvider,
    TokenUsage,
    ToolSpec,
    create_provider,
    register_provider,
    request_key,
)
from .remote import (
    FetchedChange,
    PullRequestNotFound,
    RefNotFound,
    RemoteError,
    RemoteNotReadable,
    RemoteRepo,
    RemoteUnreachable,
    ShallowHistoryExhausted,
    default_cache_root,
    open_source,
)
from .repos import (
    PathClass,
    PathKind,
    RepoAdapter,
    RepoAdapterError,
    available_adapters,
    get_adapter,
    register_adapter,
    resolve_adapter,
)
from .source import LocalCheckout, RepoSource, TreeEntry

__all__ = [
    "ChangeSet",
    "ChangeSetSpec",
    "CommitInfo",
    "Completion",
    "FetchedChange",
    "FileDiff",
    "GitError",
    "GitRepo",
    "Incident",
    "LocalCheckout",
    "Message",
    "ModelSpec",
    "PathClass",
    "PathKind",
    "Provider",
    "ProviderError",
    "PullRequestNotFound",
    "RecordingProvider",
    "RefNotFound",
    "RemoteError",
    "RemoteNotReadable",
    "RemoteRepo",
    "RemoteUnreachable",
    "RepoAdapter",
    "RepoAdapterError",
    "RepoSource",
    "ReplayMiss",
    "ReplayProvider",
    "ShallowHistoryExhausted",
    "TokenUsage",
    "ToolSpec",
    "TreeEntry",
    "available_adapters",
    "create_provider",
    "default_cache_root",
    "get_adapter",
    "mine_incidents",
    "open_source",
    "read_corpus",
    "register_adapter",
    "register_provider",
    "request_key",
    "resolve",
    "resolve_adapter",
    "summarize",
    "write_corpus",
]
